// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0yt2fsnfwSb-BPAqNh_kfJbxhvDgRH5U',
    appId: '1:1001972116267:web:29f11110c0c7e51a6ff36e',
    messagingSenderId: '1001972116267',
    projectId: 'jason-app-4c67b',
    authDomain: 'jason-app-4c67b.firebaseapp.com',
    databaseURL: 'https://jason-app-4c67b-default-rtdb.firebaseio.com',
    storageBucket: 'jason-app-4c67b.firebasestorage.app',
    measurementId: 'G-B21ZLDNE5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRY6exXeYnqRezuM_fw0eRCHIQw7D0mM',
    appId: '1:1001972116267:android:8041a6994d98f7216ff36e',
    messagingSenderId: '1001972116267',
    projectId: 'jason-app-4c67b',
    databaseURL: 'https://jason-app-4c67b-default-rtdb.firebaseio.com',
    storageBucket: 'jason-app-4c67b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArrubIkU9t_GN8KG-vT-du-F_VpdqfDGY',
    appId: '1:1001972116267:ios:9be7b206a149f9606ff36e',
    messagingSenderId: '1001972116267',
    projectId: 'jason-app-4c67b',
    databaseURL: 'https://jason-app-4c67b-default-rtdb.firebaseio.com',
    storageBucket: 'jason-app-4c67b.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArrubIkU9t_GN8KG-vT-du-F_VpdqfDGY',
    appId: '1:1001972116267:ios:9be7b206a149f9606ff36e',
    messagingSenderId: '1001972116267',
    projectId: 'jason-app-4c67b',
    databaseURL: 'https://jason-app-4c67b-default-rtdb.firebaseio.com',
    storageBucket: 'jason-app-4c67b.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0yt2fsnfwSb-BPAqNh_kfJbxhvDgRH5U',
    appId: '1:1001972116267:web:b69dd14143d9ea796ff36e',
    messagingSenderId: '1001972116267',
    projectId: 'jason-app-4c67b',
    authDomain: 'jason-app-4c67b.firebaseapp.com',
    databaseURL: 'https://jason-app-4c67b-default-rtdb.firebaseio.com',
    storageBucket: 'jason-app-4c67b.firebasestorage.app',
    measurementId: 'G-H8ESQ23Z8Z',
  );
}
